[build]
  command = "npm install && npm install autoprefixer postcss && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.6"
  NPM_VERSION = "18.12.5"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
