[build]
  command = "npm install && npm run build"
  commandOrigin: config

[build.environment]
  NODE_VERSION = "18.20.6"
  NPM_VERSION = "10.2.3"
  NEXT_TELEMETRY_DISABLED = "1"
  publish: /opt/build/repo/.next
  publishOrigin: config

[[plugins]]
- inputs: {}
  origin: config
  package = "@netlify/plugin-nextjs"
